# Generated by Django 5.1.1 on 2024-10-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_categoria_post_contenido_post_image_post_categorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='autor',
            new_name='autor_comentario',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='contenido',
            new_name='cuerpo_comentario',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagen',
        ),
    ]
