# Generated by Django 5.1.1 on 2024-10-08 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_rename_autor_comentarios_autor_comentario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comentarios',
            new_name='Comentario',
        ),
    ]
