# Generated by Django 5.1.1 on 2024-10-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_profile_bio_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagen del post', null=True, upload_to='img/posts'),
        ),
    ]
