# Generated by Django 5.1.1 on 2024-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagen del perfil', null=True, upload_to='img/posts'),
        ),
    ]
