# Generated by Django 5.1.1 on 2024-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tema', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
